apiVersion: v1
kind: Secret
metadata:
  name: owncloud-secret
  namespace: owncloud
type: Opaque
stringData:
  OWNCLOUD_DB_PASSWORD: owncloud
  OWNCLOUD_ADMIN_USERNAME: admin
  OWNCLOUD_ADMIN_PASSWORD: admin
  MYSQL_ROOT_PASSWORD: owncloud
  MYSQL_PASSWORD: owncloud
