apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: owncloud-vs
  namespace: owncloud
  annotations:
    external-dns.alpha.kubernetes.io/hostname: owncloud.kdvops.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/ttl: "120"
    external-dns.alpha.kubernetes.io/target: "6cfa1402-18c1-4f26-ae92-68762856bd62.cfargotunnel.com"
spec:
  hosts:
  - "owncloud.kdvops.com"
  gateways:
  - istio-system/kdvops-gateway
  http:
  - route:
    - destination:
        host: owncloud
        port:
          number: 8080
